"""
Pydantic schemas for telemetry payloads and API responses.

Data flow:
  Unity (C#) → WebSocket (port 8766) → TelemetryBatch → [TelemetryRecord …]
                                                            ↓
                                              scoring/features.py
                                                            ↓
                                              ScoringResult → LiveFeedback (back to Unity)
                                                            ↓
                                              dashboard /ws/dashboard → Streamlit
"""

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


# ── Ingest payloads (from Unity) ──────────────────────────────────────

class TelemetryRecord(BaseModel):
    """Single telemetry sample from Unity, published at ~20 Hz.

    ``session_id`` is generated by Unity on scene load and remains constant
    for the duration of one ride.  A fresh session_id is created on restart.

    ``unity_time`` is Unity's ``Time.time`` (seconds since scene start) and is
    used for windowed feature calculations (steering variance, HR delta, etc.).
    It is NOT wall-clock time — use ``unix_ms`` for absolute timestamps.

    ``trigger_id`` is non-empty only for the frame that fires an in-scene event
    (e.g. ``"red_light"``).  The brake-reaction-time feature uses it to measure
    the latency between the trigger frame and the first subsequent brake input.

    Head rotation is stored as a unit quaternion (x, y, z, w).  ``head_rot_w``
    defaults to 1.0 (identity) when Unity has not yet initialised the headset.
    """

    session_id: str
    unix_ms: int
    unity_time: float
    scenario_id: str = ""
    trigger_id: str = ""

    speed: float = 0.0
    steering_angle: float = 0.0
    brake_front: int = 0
    brake_rear: int = 0
    heart_rate: float = 0.0

    head_pos_x: float = 0.0
    head_pos_y: float = 0.0
    head_pos_z: float = 0.0

    head_rot_x: float = 0.0
    head_rot_y: float = 0.0
    head_rot_z: float = 0.0
    head_rot_w: float = 1.0

    record_type: str = "gameplay"  # "gameplay" | "headpose" — used to filter non-gameplay frames


class TelemetryBatch(BaseModel):
    """Batch envelope sent over WebSocket.

    Unity groups records into batches (default 10 per message) rather than
    sending one message per record.  This reduces WebSocket overhead by ~10×
    at 20 Hz.

    ``count`` and ``sent_at`` are informational fields added by the Unity client.
    They are optional (with safe defaults) so that minimal / test senders that
    omit them do not cause the entire batch to be silently dropped.
    """

    records: list[TelemetryRecord]
    count: int = 0          # informational — may differ from len(records)
    sent_at: str = ""       # ISO-8601 timestamp string from Unity


# ── Scoring output ────────────────────────────────────────────────────

class ScoringResult(BaseModel):
    """Output of the rule engine for a given sliding window.

    All scores are in [0, 100] unless noted.  Default values of 0 are returned
    when the window is empty or scoring fails — callers should treat 0 as
    "insufficient data" rather than "no stress / no risk".
    """

    stress_score: float = Field(0.0, ge=0, le=100)
    risk_score: float = Field(0.0, ge=0, le=100)
    brake_reaction_ms: float = 0.0
    head_scan_count_5s: int = 0
    steering_variance_3s: float = 0.0
    hr_delta_10s: float = 0.0


# ── API response models ──────────────────────────────────────────────

class SessionSummary(BaseModel):
    """Lightweight session metadata."""

    session_id: str
    start_unix_ms: int
    end_unix_ms: Optional[int] = None
    scenario_id: str = ""
    record_count: int = 0


class SessionDetail(SessionSummary):
    """Full session detail returned by the API."""

    latest_scores: Optional[ScoringResult] = None


class LiveLatest(BaseModel):
    """Snapshot of the latest live state."""

    session_id: str
    unix_ms: int
    speed: float
    heart_rate: float
    scores: ScoringResult


class LiveFeedback(BaseModel):
    """Feedback pushed back to Unity after each processed batch.

    Sent over the same ingest WebSocket connection so Unity can render
    real-time coaching cues (e.g. colour the HUD when stress is high).
    ``event_tag`` is reserved for future use (e.g. trigger confirmations).
    """

    stress_score: float = 0.0
    risk_score: float = 0.0
    event_tag: str = ""
    message: str = ""
