{{- if and .Values.analyticsApi.enabled .Values.analyticsApi.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: analytics-api-data-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "carvr.labels" . | nindent 4 }}
    app.kubernetes.io/name: analytics-api
    app.kubernetes.io/component: api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.analyticsApi.persistence.size }}
  {{- if .Values.global.storageClass }}
  storageClassName: {{ .Values.global.storageClass }}
  {{- end }}
{{- end }}
