{{- if and .Values.bridge.enabled .Values.bridge.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bridge-data-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "carvr.labels" . | nindent 4 }}
    app.kubernetes.io/name: bridge
    app.kubernetes.io/component: bridge
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.bridge.persistence.size }}
  {{- if .Values.global.storageClass }}
  storageClassName: {{ .Values.global.storageClass }}
  {{- end }}
{{- end }}
